### ISSUE TITLE
CoreML Shader

### ISSUE THREAD

**Issue by alelordelo** [jVirus/SceneShadertoy#5]
Hello Astemir, cool project!

You think it would be possible to have a CoreML file as a shader?

Ex: coreMl model read a texture, and writes back a modified texture?

Cheers!

**Comment by eleev** [comment]
Hi, thank you!

I think that everything is possible, with respect to constraints and context. 

What you asked is slightly more complex, than a single shader doing two different kinds of things, since there are more than a single task to be done. Those tasks (CoreML Model computation, Image Rendering and everything in between those two tasks) need to decomposed and properly architected to be reused and work as a software solution. 

Cheers
